<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\PerfLab.Harness\PerfLab.Harness.csproj" />
    <RuntimeHostConfigurationOption Include="System.GC.DynamicAdaptationMode" Value="0" />   <!-- pasted from a tuning guide -->
  </ItemGroup>
</Project>
